### ISSUE TITLE
el8 container build failure

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-coral2#111]
My `el8` container build failed with the following error

```
94.91 Exception:
94.91 Traceback (most recent call last):
94.91   File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 565, in untar_file
94.91     tarfile.data_filter(member.replace(name=fn), location)
94.91 AttributeError: module 'tarfile' has no attribute 'data_filter'
94.91 
94.91 During handling of the above exception, another exception occurred:
94.91 
94.91 Traceback (most recent call last):
94.91   File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
94.91     status = self.run(options, args)
94.91   File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 346, in run
94.91     requirement_set.prepare_files(finder)
94.91   File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 381, in prepare_files
94.91     ignore_dependencies=self.ignore_dependencies))
94.91   File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 623, in _prepare_file
94.91     session=self.session, hashes=hashes)
94.91   File "/usr/lib/python3.6/site-packages/pip/download.py", line 822, in unpack_url
94.91     hashes=hashes
94.91   File "/usr/lib/python3.6/site-packages/pip/download.py", line 664, in unpack_http_url
94.91     unpack_file(from_path, location, content_type, link)
94.91   File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 622, in unpack_file
94.91     untar_file(filename, location)
94.91   File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 566, in untar_file
94.91     except tarfile.LinkOutsideDestinationError:
94.91 AttributeError: module 'tarfile' has no attribute 'LinkOutsideDestinationError'
------
Dockerfile:14
--------------------
  13 |     
  14 | >>> RUN sudo yum install -y python3-pip \
  15 | >>>     && sudo pip3 install kubernetes
  16 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c sudo yum install -y python3-pip     && sudo pip3 install kubernetes" did not complete successfully: exit code: 2
```

It looks like pip is using features of the `tarfile` module which were introduced in Python 3.8.

**Comment by jameshcorbett** [comment]
@grondo any suggestions for how to fix this?

**Comment by vsoch** [comment]
> It looks like pip is using features of the tarfile module which were introduced in Python 3.8.

Yep that's it :)

I'm not grondo, but (as you found) tarfile is a system provided module and that exception type `` wasn't added until 3.8 (first appears here https://docs.python.org/3.8/library/tarfile.html) Did you try:

```
$ python3 --version
Python 3.6.8

$ python3 -m pip install kubernetes
```
in case the pip you are installing is a newer one? And of course with sudo if needed (not sure about your environment).

**Comment by grondo** [comment]
`pip3` is already installed in the el8 flux-sched image. Try just removing the `yum install -y python3-pip`. My intuition is that this upgrading `pip` to a version that doesn't work with the rest of the distro (yes, a packaging error).

**Comment by grondo** [comment]
Yeah, this fixes it for me:
```diff
diff --git a/src/test/docker/el8/Dockerfile b/src/test/docker/el8/Dockerfile
index 10bcb0c..a35ecfe 100644
--- a/src/test/docker/el8/Dockerfile
+++ b/src/test/docker/el8/Dockerfile
@@ -11,8 +11,7 @@ RUN \
    && sudo usermod -G wheel $USER; \
  fi
 
-RUN sudo yum install -y python3-pip \
-    && sudo pip3 install kubernetes
+RUN sudo pip3 install kubernetes
 
 COPY ./kubectl.sh ./sync-kube-config.sh /usr/local/share/
 RUN sudo chmod 755 /usr/local/share/kubectl.sh \
```

If you need the latest pip3, you might have to first upgrade all packages in the distro. However, this could destabilize the installed flux-core and flux-sched code since it wasn't built with all the updated packages.

**Comment by vsoch** [comment]
>  Try just removing the yum install -y python3-pip.

I missed you were installing it again! In my example above, I don't do an install (but just use the one in the container). Glad that worked!
